//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace phatnguyen
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PNPdataEntities : DbContext
    {
        public PNPdataEntities()
            : base("name=PNPdataEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tbBill_> tbBill_ { get; set; }
        public virtual DbSet<tbBillDetails_> tbBillDetails_ { get; set; }
        public virtual DbSet<tbCustomer_> tbCustomer_ { get; set; }
        public virtual DbSet<tbLogin> tbLogins { get; set; }
        public virtual DbSet<tbProduct_> tbProduct_ { get; set; }
        public virtual DbSet<tbSalary_> tbSalary_ { get; set; }
        public virtual DbSet<tbStaff_> tbStaff_ { get; set; }
        public virtual DbSet<tbStatistic_> tbStatistic_ { get; set; }
        public virtual DbSet<tbWarehouse_> tbWarehouse_ { get; set; }
    }
}
