//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace phatnguyen
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbBillDetails_
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbBillDetails_()
        {
            this.tbStatistic_ = new HashSet<tbStatistic_>();
        }
    
        public int ID { get; set; }
        public Nullable<int> ProductID { get; set; }
        public string ProductName { get; set; }
        public string ProductCode { get; set; }
        public Nullable<int> BillID { get; set; }
        public string BillCode { get; set; }
        public Nullable<int> Amount { get; set; }
        public Nullable<double> UnitPrice { get; set; }
        public Nullable<double> Discount { get; set; }
        public Nullable<double> IntoMoney { get; set; }
    
        public virtual tbBill_ tbBill_ { get; set; }
        public virtual tbProduct_ tbProduct_ { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbStatistic_> tbStatistic_ { get; set; }
    }
}
