//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace phatnguyen
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbSalary_
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbSalary_()
        {
            this.tbStatistic_ = new HashSet<tbStatistic_>();
        }
    
        public int ID { get; set; }
        public Nullable<int> StaffID { get; set; }
        public string StaffCode { get; set; }
        public string StaffName { get; set; }
        public Nullable<int> Hours_work { get; set; }
        public Nullable<double> Bonus { get; set; }
        public Nullable<double> Total_Salary { get; set; }
    
        public virtual tbStaff_ tbStaff_ { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbStatistic_> tbStatistic_ { get; set; }
    }
}
