//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace phatnguyen
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbStatistic_
    {
        public int ID { get; set; }
        public Nullable<int> Total_amount_of_bill { get; set; }
        public Nullable<double> C_Total_salary_of_Staff { get; set; }
        public Nullable<double> Revuene { get; set; }
        public Nullable<double> Profit { get; set; }
        public Nullable<int> BillIDDetails { get; set; }
        public Nullable<int> SalaryID { get; set; }
        public Nullable<int> ProductID { get; set; }
    
        public virtual tbBillDetails_ tbBillDetails_ { get; set; }
        public virtual tbProduct_ tbProduct_ { get; set; }
        public virtual tbSalary_ tbSalary_ { get; set; }
    }
}
