//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace phatnguyen
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbWarehouse_
    {
        public int ID { get; set; }
        public Nullable<int> ProductID { get; set; }
        public string ProductName { get; set; }
        public string State { get; set; }
        public string ProductCode { get; set; }
    
        public virtual tbProduct_ tbProduct_ { get; set; }
    }
}
